import { createThemedStyleSheet } from '../../config/theme';

export default createThemedStyleSheet((colors) => ({
  container: { flex: 1 },
  inner:     { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 20 },
  title:     { color: colors.textPrimary, fontSize: 24, fontWeight: '800', marginBottom: 20 },
  empty:     { color: colors.mutedText, fontSize: 15, textAlign: 'center', marginTop: 40 },
  habitRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: 14, padding: 16, marginBottom: 10, borderWidth: 1, borderColor: colors.surfaceAlt },
  emojiCircle: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', marginRight: 14 },
  emojiText:   { fontSize: 22 },
  habitInfo:   { flex: 1 },
  habitName:   { color: colors.textPrimary, fontSize: 16, fontWeight: '700' },
  habitSub:    { color: colors.mutedText, fontSize: 12, marginTop: 3 },
  rowActions:  { flexDirection: 'row', alignItems: 'center', gap: 6 },
  // actionBtn:   { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.surfaceSoft, alignItems: 'center', justifyContent: 'center' },
  actionBtn: {
    width: 30, height: 30, borderRadius: 9,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: colors.background, borderWidth: 1, borderColor: colors.surfaceAlt,
  },
  chevron:     { color: colors.mutedText, fontSize: 22, marginLeft: 2 },
  fab: { position: 'absolute', bottom: 24, right: 20, width: 58, height: 58, borderRadius: 29, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', shadowColor: colors.shadow, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 8, elevation: 8, zIndex: 20 },
  fabText: { color: colors.textPrimary, fontSize: 30, fontWeight: '300', lineHeight: 34 },
  overlay:  { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...require('react-native').StyleSheet.absoluteFillObject, backgroundColor: colors.backdrop },
  sheet:    { backgroundColor: colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: 44 },
  handle:   { width: 40, height: 4, backgroundColor: colors.surfaceAlt, borderRadius: 2, alignSelf: 'center', marginBottom: 20 },
  sheetTitle: { color: colors.textPrimary, fontSize: 20, fontWeight: '700', marginBottom: 16 },
  sheetLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '600', marginBottom: 10, marginTop: 4 },
  input: { backgroundColor: colors.background, borderWidth: 1, borderColor: colors.surfaceAlt, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, color: colors.textPrimary, fontSize: 15, marginBottom: 16 },
  emojiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  emojiOption: { width: 44, height: 44, borderRadius: 10, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.surfaceAlt },
  emojiOptionActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  emojiOptionText:   { fontSize: 22 },
  colorRow: { flexDirection: 'row', gap: 10, marginBottom: 24 },
  colorDot: { width: 30, height: 30, borderRadius: 15 },
  colorDotActive: { borderWidth: 3, borderColor: colors.textPrimary },
  addBtn:         { backgroundColor: colors.primary, borderRadius: 14, paddingVertical: 15, alignItems: 'center' },
  addBtnDisabled: { opacity: 0.4 },
  addBtnText:     { color: colors.textPrimary, fontWeight: '700', fontSize: 16 },
}));
