import { createThemedStyleSheet } from "../../config/theme";

export default createThemedStyleSheet((colors) => ({
  container: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 40 },
  title: { color: colors.textPrimary, fontSize: 24, fontWeight: "800", marginBottom: 16 },
  monthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    marginBottom: 16,
  },
  navBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
  },
  monthText: { color: colors.textPrimary, fontSize: 17, fontWeight: "800" },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    padding: 16,
    marginBottom: 16,
  },
  label: { color: colors.textSecondary, fontSize: 13, marginBottom: 8, fontWeight: "700" },
  inputRow: { flexDirection: "row", gap: 10 },
  input: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    color: colors.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  saveBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  saveText: { color: colors.background, fontWeight: "900" },
  error: { color: colors.danger, marginTop: 8, fontSize: 12 },
  progressCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    padding: 18,
    marginBottom: 16,
  },
  ringWrap: { alignItems: "center", marginBottom: 18 },
  ringOuter: {
    width: 190,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.primary,
    overflow: "hidden",
    alignSelf: "stretch",
    marginHorizontal: 10,
  },
  ringInner: {
    alignSelf: "flex-end",
    height: "100%",
    backgroundColor: colors.surfaceAlt,
  },
  percent: { color: colors.textPrimary, fontSize: 36, fontWeight: "900", marginTop: 14 },
  used: { color: colors.mutedText, fontSize: 12, fontWeight: "700" },
  amountGrid: { gap: 10 },
  amountBox: {
    backgroundColor: colors.background,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
  },
  boxLabel: { color: colors.mutedText, fontSize: 12, marginBottom: 4 },
  boxValue: { color: colors.textPrimary, fontSize: 16, fontWeight: "800" },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 12,
  },
  dailyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 7,
  },
  dailyLabel: { color: colors.textSecondary, fontSize: 13 },
  dailyValue: { color: colors.textPrimary, fontSize: 13, fontWeight: "800" },
  barTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.surfaceAlt,
    overflow: "hidden",
    marginTop: 12,
  },
  barFill: { height: "100%", backgroundColor: colors.primary },
}));
