import { createThemedStyleSheet } from "../../config/theme";

export default createThemedStyleSheet((colors) => ({
  screen: { flex: 1 },
  container: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 40 },
  title: { color: colors.textPrimary, fontSize: 24, fontWeight: "800", marginBottom: 6 },
  description: { color: colors.mutedText, fontSize: 13, marginBottom: 18 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    padding: 14,
    marginBottom: 16,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionBody: { marginTop: 12 },
  totalCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    marginBottom: 16,
  },
  totalLabel: { color: colors.mutedText, fontSize: 13, fontWeight: "700" },
  totalValue: { color: colors.primary, fontSize: 32, fontWeight: "900", marginTop: 6 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 14 },
  categoryBox: {
    width: "48%",
    backgroundColor: colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    padding: 12,
  },
  categoryLabel: { color: colors.mutedText, fontSize: 12, fontWeight: "700" },
  categoryValue: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "900",
    marginTop: 5,
  },
  input: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    borderRadius: 12,
    color: colors.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
    marginBottom: 10,
  },
  dropdown: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  placeholder: { color: colors.mutedText },
  selectedText: { color: colors.textPrimary, fontWeight: "700" },
  inputRow: { flexDirection: "row", gap: 10 },
  rowInput: { flex: 1 },
  addBtn: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  addBtnText: { color: colors.background, fontSize: 14, fontWeight: "900" },
  saveBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  saveBtnDisabled: { opacity: 0.65 },
  saveText: { color: colors.background, fontSize: 14, fontWeight: "900" },
  cancelBtn: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  cancelText: { color: colors.textPrimary, fontSize: 14, fontWeight: "800" },
  error: { color: colors.danger, marginTop: 8, fontSize: 12 },
  item: { borderTopWidth: 1, borderTopColor: colors.surfaceAlt, paddingVertical: 12 },
  itemTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  itemCategory: { color: colors.textPrimary, fontSize: 15, fontWeight: "900" },
  itemMeta: { color: colors.mutedText, fontSize: 12, marginTop: 4 },
  itemAmount: { color: colors.primary, fontSize: 16, fontWeight: "900" },
  itemNote: { color: colors.textSecondary, fontSize: 13, marginTop: 6 },
  actionRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  smallBtn: {
    flexDirection: "row",
    gap: 5,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: "center",
  },
  dangerBtn: { backgroundColor: colors.dangerSoft },
  smallBtnText: { color: colors.textPrimary, fontSize: 12, fontWeight: "800" },
  dangerText: { color: colors.danger },
  emptyText: {
    color: colors.mutedText,
    fontSize: 13,
    textAlign: "center",
    paddingVertical: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.backdrop,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalSheet: {
    width: "100%",
    maxHeight: "70%",
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    padding: 14,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 10,
  },
  modalOption: { paddingVertical: 13 },
  modalOptionText: { color: colors.textPrimary, fontSize: 15, fontWeight: "700" },
  modalSeparator: { height: 1, backgroundColor: colors.surfaceAlt },
  overlay: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    ...require('react-native').StyleSheet.absoluteFillObject,
    backgroundColor: colors.backdrop,
  },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    borderColor: colors.surfaceAlt,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 26,
  },
  handle: {
    alignSelf: "center",
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.surfaceAlt,
    marginBottom: 14,
  },
  sheetTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 14,
  },
}));
