export const WORDINGS = {
  common: {
    add: 'Add',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    saveChanges: 'Save Changes',
    saveFailed: 'Save Failed',
    deleteFailed: 'Delete Failed',
    unableToDelete: 'Unable to delete. Please try again.',
    unableToSave: 'Unable to save. Please try again.',
    saving: 'Saving...',
    more: 'More',
    comingSoon: 'Coming soon',
    pleaseTryAgain: 'Please try again.',
    loading: 'Loading...',
    deleteMessage: (name) => `Delete "${name}"? This can't be undone.`,
  },
  nav: {
    today: 'Today',
    todos: 'Todos',
    finance: 'Finance',
    habits: 'Habits',
    more: 'More',
    financeCalendar: 'Finance Calendar',
    financeGraph: 'Finance Graph',
    budget: 'Budget',
    savings: 'Savings',
    calculator: 'Calculator',
    notes: 'Notes',
    reminders: 'Reminders',
    profile: 'Profile',
    settings: 'Settings',
    splitBills: 'Split Bills',
  },
  splitBills: {
    title: 'Split Bills',
    expensesTab: 'Expenses',
    balanceTab: 'Balance',
    groupsTab: 'Groups',
    peopleTab: 'People',
    expensesSubtitle: 'Track what was paid and how it should be split.',
    balanceSubtitle: 'See who owes what after each shared expense.',
    groupsSubtitle: 'Manage split bill groups and their members.',
    peopleSubtitle: 'Add the people involved in your shared bills.',
    noExpenses: 'No expenses yet.',
    noSettled: 'Everyone is settled.',
    noPeople: 'No people added yet.',
    noGroups: 'No groups created yet.',
    newExpense: 'New Expense',
    editExpense: 'Edit Expense',
    addPerson: 'Add Person',
    description: 'Description',
    amount: 'Amount',
    paidBy: 'Paid by',
    date: 'Date',
    splitWith: 'Split with',
    group: 'Group',
    groupName: 'Group Name',
    groupNamePlaceholder: 'Group name',
    members: 'Members',
    splitTypeLabel: 'Split Type',
    amountPerPerson: 'Amount per person',
    percentagePerPerson: 'Percentage per person',
    personName: 'Name',
    enterPersonName: 'Enter a person name',
    expenseDeleteConfirm: (name) => `Delete "${name}"? This can't be undone.`,
    personDeleteConfirm: (name) => `Delete "${name}"? This can't be undone.`,
  },
  graph: {
    title: 'Finance Graph',
    subtitle: 'Coming soon',
    description: 'Finance graph insights will be available here soon.',
    screenDescription: 'Income vs expenses over the year, and where your money is going by category.',
    tabOverview: 'Overview',
    tabIncome: 'Income',
    tabExpense: 'Expenses',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expenses',
    net: 'Net',
    monthlyTrendTitle: 'Monthly Trend',
    monthlyTrendSubtitle: (year) => `Income vs Expenses for ${year}`,
    incomeByCategoryTitle: 'Income by Category',
    expenseByCategoryTitle: 'Expenses by Category',
    yearSubtitle: (year) => `Totals for ${year}`,
    loading: 'Loading finance data...',
    emptyIncome: 'No income recorded for this year yet.',
    emptyExpense: 'No expenses recorded for this year yet.',
    loadError: 'Could not load finance data',
  },
  savings: {
    title: 'Savings',
    description: 'Savings are tracked separately from finances.',
    total: 'Total Savings',
    add: 'Add Saving',
    edit: 'Edit Saving',
    records: 'Saving Records',
    loading: 'Loading savings...',
    empty: 'No savings added yet.',
    selectCategory: 'Select Saving Category',
    categoryPlaceholder: 'Saving category',
    amountPlaceholder: 'Amount',
    datePlaceholder: 'YYYY-MM-DD',
    notePlaceholder: 'Note',
    categoryRequired: 'Please select a saving category.',
    amountRequired: 'Please enter a valid saving amount.',
    deleteTitle: 'Delete Saving',
    deleteMessage: (amount, category) => `Delete ${amount} from ${category}? This can't be undone.`,
    uncategorized: 'Uncategorized',
  },
  settings: {
    title: 'Settings',
    description: 'Customize categories used by Finance, Savings, and Todos.',
    incomeCategories: 'Income Categories',
    expenseCategories: 'Expense Categories',
    savingCategories: 'Saving Categories',
    todoCategories: 'Todo Categories',
    newCategory: 'New category',
    newSubcategory: 'New subcategory',
    newSavingCategory: 'New saving category',
    newTodoCategory: 'New todo category',
    subcategories: 'Subcategories',
    categoryNotSavedTitle: 'Category not saved yet',
    categoryNotSavedMessage: 'Please run the migration SQL and reload the app before editing fallback categories.',
    subcategoryNotSavedMessage: 'Please run the migration SQL and reload the app before editing fallback subcategories.',
    categoryNotSavedDeleteMessage: 'Please run the migration SQL and reload the app before deleting fallback categories.',
    subcategoryNotSavedDeleteMessage: 'Please run the migration SQL and reload the app before deleting fallback subcategories.',
    categoryNotSavedAddSubMessage: 'Please run the migration SQL and reload the app before adding subcategories.',
    deleteCategoryTitle: 'Delete Category',
    deleteSubcategoryTitle: 'Delete Subcategory',
    deleteTodoCategoryTitle: 'Delete Todo Category',
    deleteSavingCategoryTitle: 'Delete Saving Category',
    deleteCategoryMessage: (name) => `Delete "${name}"? This can't be undone.`,
    deleteSubcategoryMessage: (sub, name) => `Delete "${sub}" from "${name}"? This can't be undone.`,
    deleteSavingCategoryMessage: (label) => `Delete "${label}"? Existing saving records will keep their category name. This can't be undone.`,
  },
  profile: {
    title: 'Profile',
    email: 'Email',
    theme: 'Theme',
    darkTheme: 'Dark Theme',
    lightTheme: 'Light Theme',
    signOut: 'Sign Out',
    signOutMessage: 'Are you sure you want to sign out?',
    quickAccess: 'Customize Quick Access',
  },
  auth: {
    forgotPassword: 'Forgot password?',
    backToSignIn: 'Back to sign in',
    resetTitle: 'Reset your password',
    resetStep1Description: "Enter your account email — we'll send you a reset link. Click that link and this app will open the reset-password screen automatically.",
    resetStep2Description: (email) => `We've sent an email to ${email}. Click the "Reset Password" link in it to continue — this app will pick it up automatically and let you set a new password.\n\nIf your email instead shows a verification code, you can enter it below along with your new password.`,
    codeLabel: 'Verification code',
    codePlaceholder: '6-digit code',
    newPasswordLabel: 'New password',
    confirmNewPasswordLabel: 'Confirm new password',
    sendCode: 'Send code',
    verifyAndReset: 'Reset password',
    resendCode: 'Resend code',
    codeSent: (email) => `A verification code has been sent to ${email}. Enter it below along with your new password.`,
    resetSuccess: 'Your password has been reset. You can now sign in with your new password.',
  },
  errors: {
    auth: 'Auth error',
    sessionExpired: 'Session expired',
    invalidResetCode: 'That code is invalid or has expired. Please request a new one.',
    addCategory: 'Could not add category',
    updateCategory: 'Could not update category',
    deleteCategory: 'Could not delete category',
    addSubcategory: 'Could not add subcategory',
    updateSubcategory: 'Could not update subcategory',
    deleteSubcategory: 'Could not delete subcategory',
    addTodoCategory: 'Could not add todo category',
    updateTodoCategory: 'Could not update todo category',
    deleteTodoCategory: 'Could not delete todo category',
    addSavingCategory: 'Could not add saving category',
    updateSavingCategory: 'Could not update saving category',
    deleteSavingCategory: 'Could not delete saving category',
    updateColor: 'Could not update color',
    updateIcon: 'Could not update icon',
  },
  dayfinance:{
    title: 'Finance',
    notransactions: 'No transactions yet. Tap + to add one!',
    expense: 'Expenses',
    balance: 'Balance',
    transactions: 'Transactions',
    confirmDelete: 'Delete Transaction',
    deleteMessage: (category) => `Delete "${category}"? This can't be undone.`,
  },
  addTransaction: {
    category: 'Category',
    subcategory: 'Subcategory',
    amount: 'Amount (LKR)',
  },
  habits: {
    streak: '🔥 Streak',
    thisMonth: '✅ This Month',
    rate: '📊 Rate',
    hint: 'Tap a day to mark / unmark it',
    notDone: 'Not done',
    completed: 'Completed',
    today: 'Today',
    empty: 'No habits yet. Tap + to add your first one!',
    haveStreak: (count) => `🔥 ${count} day streak`,
    noStreak: 'No streak yet',
    confirmDelete: 'Delete Habit',
    editHabit: 'Edit Habit',
    newHabit: 'New Habit',
    habitNamePlaceholder: 'Habit name  (e.g. Exercise)',
    iconLabel: 'Icon',
    colorLabel: 'Color',
  },
  notes: {
    title: 'Notice',
    empty: 'No notices yet. Tap + to add one!',
    confirmDelete: 'Delete Notice',
    deleteMessage: (title) => `Delete "${title}"? This can't be undone.`,
    editNotice: 'Edit Notice',
    newNotice: 'New Notice',
    noticeTitlePlaceholder: 'Notice title',
    noticeBodyPlaceholder: '"Write your note...',
    addNote: 'Add Notice',
  },
  reminders: {
    title: 'Reminders',
    description: 'Set daily reminders. Toggle on/off and tap the time to change it.',
    bell: '🔔',
    dailyReminder: 'Daily reminder',
    remindMeAt: 'Remind me at',
    willRemindAt: 'Will remind at',
    permWarn: '⚠️ Notifications are disabled. Enable them in device Settings.',
    setReminderTime: 'Set Reminder Time',
  },
  todaysummary: {
    todoTitle: 'Todos',
    habitTitle: 'Habits',
    financeTitle: 'Finance',
    quickAccess: 'Quick Access',
    completedTodos: (todoCompleted, todoTotal) => `${todoCompleted} / ${todoTotal} completed`,
    completedHabits: (habitsDone, habitsTotal) => `${habitsDone} of ${habitsTotal} done today`,
  },
  todo: {
    titleRequired: 'Please give this task a title',
    titleTooLong: 'Title should be under 60 characters',
    categoryRequired: 'Please choose a category',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Meeting: UX Case',
    notesLabel: 'Notes',
    notesPlaceholder: 'Add any details (optional)',
    EditTask: 'Edit Task',
    NewTask: 'New Task',
    categoryLabel: 'Category',
    dateLabel: 'Date',
    Alarm: 'Alarm',
    deleteTask: 'Delete Task',
    title: 'Todo List',
    noCompletedTasks: 'Nothing completed yet',
    noActiveTasks: 'All caught up for this day',
    noTasks: 'No tasks for this day',
    confirmDelete: 'Delete Task',
    deleteMessage: (title) => `Delete "${title}"? This can't be undone.`,
    deleteMessage2: "Are you sure you want to delete this task? This can't be undone."
  }
};
