export const WORDINGS = {
  common: {
    add: 'Add',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    more: 'More',
    comingSoon: 'Coming soon',
    pleaseTryAgain: 'Please try again.',
  },
  nav: {
    today: 'Today',
    todos: 'Todos',
    finance: 'Finance',
    habits: 'Habits',
    more: 'More',
    financeCalendar: 'Finance Calendar',
    financeGraph: 'Finance Graph',
    budget: 'Budget',
    savings: 'Savings',
    calculator: 'Calculator',
    notes: 'Notes',
    reminders: 'Reminders',
    profile: 'Profile',
    settings: 'Settings',
  },
  graph: {
    title: 'Finance Graph',
    subtitle: 'Coming soon',
    description: 'Finance graph insights will be available here soon.',
    screenDescription: 'Income vs expenses over the year, and where your money is going by category.',
    tabOverview: 'Overview',
    tabIncome: 'Income',
    tabExpense: 'Expenses',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expenses',
    net: 'Net',
    monthlyTrendTitle: 'Monthly Trend',
    monthlyTrendSubtitle: (year) => `Income vs Expenses for ${year}`,
    incomeByCategoryTitle: 'Income by Category',
    expenseByCategoryTitle: 'Expenses by Category',
    yearSubtitle: (year) => `Totals for ${year}`,
    loading: 'Loading finance data...',
    emptyIncome: 'No income recorded for this year yet.',
    emptyExpense: 'No expenses recorded for this year yet.',
    loadError: 'Could not load finance data',
  },
  savings: {
    title: 'Savings',
    description: 'Savings are tracked separately from finances.',
    total: 'Total Savings',
    add: 'Add Saving',
    edit: 'Edit Saving',
    records: 'Saving Records',
    loading: 'Loading savings...',
    empty: 'No savings added yet.',
    selectCategory: 'Select Saving Category',
    categoryPlaceholder: 'Saving category',
    amountPlaceholder: 'Amount',
    datePlaceholder: 'YYYY-MM-DD',
    notePlaceholder: 'Note',
    categoryRequired: 'Please select a saving category.',
    amountRequired: 'Please enter a valid saving amount.',
    deleteTitle: 'Delete Saving',
    deleteMessage: (amount, category) => `Delete ${amount} from ${category}? This can't be undone.`,
    uncategorized: 'Uncategorized',
  },
  settings: {
    title: 'Settings',
    description: 'Customize categories used by Finance, Savings, and Todos.',
    incomeCategories: 'Income Categories',
    expenseCategories: 'Expense Categories',
    savingCategories: 'Saving Categories',
    todoCategories: 'Todo Categories',
    newCategory: 'New category',
    newSubcategory: 'New subcategory',
    newSavingCategory: 'New saving category',
    newTodoCategory: 'New todo category',
    subcategories: 'Subcategories',
    categoryNotSavedTitle: 'Category not saved yet',
    categoryNotSavedMessage: 'Please run the migration SQL and reload the app before editing fallback categories.',
    subcategoryNotSavedMessage: 'Please run the migration SQL and reload the app before editing fallback subcategories.',
    categoryNotSavedDeleteMessage: 'Please run the migration SQL and reload the app before deleting fallback categories.',
    subcategoryNotSavedDeleteMessage: 'Please run the migration SQL and reload the app before deleting fallback subcategories.',
    categoryNotSavedAddSubMessage: 'Please run the migration SQL and reload the app before adding subcategories.',
    deleteCategoryTitle: 'Delete Category',
    deleteSubcategoryTitle: 'Delete Subcategory',
    deleteTodoCategoryTitle: 'Delete Todo Category',
    deleteSavingCategoryTitle: 'Delete Saving Category',
    deleteCategoryMessage: (name) => `Delete "${name}"? This can't be undone.`,
    deleteSubcategoryMessage: (sub, name) => `Delete "${sub}" from "${name}"? This can't be undone.`,
    deleteSavingCategoryMessage: (label) => `Delete "${label}"? Existing saving records will keep their category name. This can't be undone.`,
  },
  profile: {
    title: 'Profile',
    email: 'Email',
    theme: 'Theme',
    darkTheme: 'Dark Theme',
    lightTheme: 'Light Theme',
    signOut: 'Sign Out',
    signOutMessage: 'Are you sure you want to sign out?',
  },
  auth: {
    forgotPassword: 'Forgot password?',
    backToSignIn: 'Back to sign in',
    resetTitle: 'Reset your password',
    resetStep1Description: "Enter your account email — we'll send you a reset link. Click that link and this app will open the reset-password screen automatically.",
    resetStep2Description: (email) => `We've sent an email to ${email}. Click the "Reset Password" link in it to continue — this app will pick it up automatically and let you set a new password.\n\nIf your email instead shows a verification code, you can enter it below along with your new password.`,
    codeLabel: 'Verification code',
    codePlaceholder: '6-digit code',
    newPasswordLabel: 'New password',
    confirmNewPasswordLabel: 'Confirm new password',
    sendCode: 'Send code',
    verifyAndReset: 'Reset password',
    resendCode: 'Resend code',
    codeSent: (email) => `A verification code has been sent to ${email}. Enter it below along with your new password.`,
    resetSuccess: 'Your password has been reset. You can now sign in with your new password.',
  },
  errors: {
    auth: 'Auth error',
    sessionExpired: 'Session expired',
    invalidResetCode: 'That code is invalid or has expired. Please request a new one.',
    addCategory: 'Could not add category',
    updateCategory: 'Could not update category',
    deleteCategory: 'Could not delete category',
    addSubcategory: 'Could not add subcategory',
    updateSubcategory: 'Could not update subcategory',
    deleteSubcategory: 'Could not delete subcategory',
    addTodoCategory: 'Could not add todo category',
    updateTodoCategory: 'Could not update todo category',
    deleteTodoCategory: 'Could not delete todo category',
    addSavingCategory: 'Could not add saving category',
    updateSavingCategory: 'Could not update saving category',
    deleteSavingCategory: 'Could not delete saving category',
    updateColor: 'Could not update color',
    updateIcon: 'Could not update icon',
  },
};
