import { createThemedStyleSheet } from '../../config/theme';

export default createThemedStyleSheet((colors) => ({
  container: { paddingHorizontal: 24, paddingTop: 56, paddingBottom: 40 },
  title: { color: colors.textPrimary, fontSize: 24, fontWeight: '800', marginBottom: 6 },
  description: { color: colors.mutedText, fontSize: 13, marginBottom: 18 },
  card: { backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.surfaceAlt, padding: 14, marginBottom: 16 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionBody: { marginTop: 12 },
  cardTitle: { color: colors.textPrimary, fontSize: 17, fontWeight: '800' },
  addRow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginTop: 8 },
  input: { flex: 1, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.surfaceAlt, borderRadius: 10, color: colors.textPrimary, paddingHorizontal: 12, paddingVertical: 9, fontSize: 13 },
  smallBtn: { flexDirection: 'row', gap: 4, backgroundColor: colors.surfaceAlt, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9, alignItems: 'center' },
  smallBtnText: { color: colors.textPrimary, fontSize: 12, fontWeight: '700' },
  dangerBtn: { backgroundColor: colors.dangerSoft },
  dangerText: { color: colors.danger },
  categoryBox: { borderTopWidth: 1, borderTopColor: colors.surfaceAlt, paddingTop: 12, marginTop: 12 },
  categoryHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  categoryName: { flex: 1, color: colors.textPrimary, fontSize: 14, fontWeight: '800' },
  subCount: { color: colors.mutedText, fontSize: 11, fontWeight: '700', marginRight: 8 },
  subTitle: { color: colors.mutedText, fontSize: 11, fontWeight: '700', marginTop: 12, marginBottom: 6 },
  subRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 5 },
  subName: { flex: 1, color: colors.textSecondary, fontSize: 13 },
  iconBtn: { width: 30, height: 30, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background },
  todoRow: { borderTopWidth: 1, borderTopColor: colors.surfaceAlt, paddingTop: 12, marginTop: 12, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  colorDot: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  savingIcon: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary },
  styleRow: { flexBasis: '100%', flexDirection: 'row', gap: 8, marginLeft: 40, flexWrap: 'wrap' },
  colorPick: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: 'transparent' },
  iconPick: { width: 28, height: 28, borderRadius: 9, borderWidth: 1, borderColor: colors.surfaceAlt, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' },
  pickActive: { borderColor: colors.primary },
}));
